project:
  type: website
  output-dir: docs

website:
  title: "𓆞 lung.fish Data Explorer"
  repo-url: https://github.com/Lungfish-science/wastewater-dashboard
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Dashboards"
        menu:
          - href: dashboard1.qmd
            text: Wastewater Dashboard
          - href: https://dholab.github.io/public_viz/001-make-by-city-and-by-virus-dashboards/index.html
            text: Virus Report Cards
          - href: https://dholab.github.io/public_viz/004-rhinovirus-serotypes-dashboards/
            text: Rhinovirus Serotypes
          - href: https://dholab.github.io/public_viz/003-dane-county-school-biomark-x-dashboards/
            text: Air Sampling in Dane County, WI Schools
          - href: https://dholab.github.io/public_viz/005-12s-species/
            text: Species Frequency Dashboard
          - href: https://dholab.github.io/public_viz/006-cryptic-lineages/index.html
            text: SARS-CoV-2 Cryptic Lineages

      - acknowledgements.qmd
      - text: "Help"
        menu:
          - text: "Report a Bug"
            icon: "bug"
            href: "https://github.com/Lungfish-science/wastewater-dashboard/issues"
          - text: "Ask a Question"
            icon: "chat-right-text"
            href: "https://github.com/Lungfish-science/wastewater-dashboard/discussions"
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/Lungfish-science/wastewater-dashboard
          - text: Report a Bug
            href:  https://github.com/Lungfish-science/wastewater-dashboard/issues
    collapse: true
    collapse-below: lg
    toggle-position: right
  back-to-top-navigation: true
  page-navigation: true
  reader-mode: true

  page-footer:
    left: "Copyright 2025, lung.fish"
    center: |
      **DISCLAIMER:**
      The raw data published on this dashboard has been obtained from deidentified and aggregated materials collected in accordance with the law and ethical guidelines governing the research studies. This data is made available for informational purposes only. This data set has not been independently verified, validated, or peer reviewed. It may contain errors, omissions, or artifacts inherent to the methods used in data collection and processing and is provided as is without any warranty of accuracy or completeness.

      This data is neither intended for clinical or diagnostic purposes nor should it be used for making public policy. Users must not rely on this dataset to inform health care decisions, public health strategies, or regulatory actions. Any conclusions drawn from this data are the sole responsibility of the user.

      By accessing or using this data, you assume all risks and acknowledge these limitations. You further agree to use this data responsibly, in compliance with all applicable legal and ethical standards.
    right:
      - text: "About"
        href: about.qmd
      - text: "License"
        href: https://github.com/Lungfish-science/wastewater-dashboard/blob/main/LICENSE
      - icon: github
        href: https://github.com/inkfishmedical

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

# execute:
#   freeze: auto
